// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package scm

import mock "github.com/stretchr/testify/mock"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// SetName provides a mock function with given fields: _a0
func (_m *Repository) SetName(_a0 string) {
	_m.Called(_a0)
}
